CREATE TABLE association
(
    id_assiciation SERIAL PRIMARY KEY NOT NULL,
    id CHARACTER VARYING,
    id_ex CHARACTER VARYING,
    siret CHARACTER VARYING,
    rup_mi CHARACTER VARYING,
    gestion CHARACTER VARYING,
    date_creat CHARACTER VARYING,
    date_decla CHARACTER VARYING,
    date_publi CHARACTER VARYING,
    date_disso CHARACTER VARYING,
    nature CHARACTER VARYING,
    groupement CHARACTER VARYING,
    titre CHARACTER VARYING,
    titre_court CHARACTER VARYING,
    objet CHARACTER VARYING,
    objet_social1 CHARACTER VARYING,
    objet_social2 CHARACTER VARYING,
    adrs_complement CHARACTER VARYING,
    adrs_numvoie CHARACTER VARYING,
    adrs_repetition CHARACTER VARYING,
    adrs_typevoie CHARACTER VARYING,
    adrs_libvoie CHARACTER VARYING,
    adrs_distrib CHARACTER VARYING,
    adrs_codeinsee CHARACTER VARYING,
    adrs_codepostal CHARACTER VARYING,
    adrs_libcommune CHARACTER VARYING,
    adrg_declarant CHARACTER VARYING,
    adrg_complemid CHARACTER VARYING,
    adrg_complemgeo CHARACTER VARYING,
    adrg_libvoie CHARACTER VARYING,
    adrg_distrib CHARACTER VARYING,
    adrg_codepostal CHARACTER VARYING,
    adrg_achemine CHARACTER VARYING,
    adrg_pays CHARACTER VARYING,
    dir_civilite CHARACTER VARYING,
    siteweb CHARACTER VARYING,
    publiweb CHARACTER VARYING,
    observation CHARACTER VARYING,
    position CHARACTER VARYING,
    maj_time CHARACTER VARYING,
    mois_crea CHARACTER VARYING,
    mois_ferm CHARACTER VARYING,
    objet_social_parent_id CHARACTER VARYING,
    objet_social_lib CHARACTER VARYING,
    objet_social_parent_lib CHARACTER VARYING,
    reg CHARACTER VARYING,
    dep CHARACTER VARYING
)
TABLESPACE pg_default;


